spring:
  application:
    name: spring security 01
  thymeleaf:
    cache: true
  messages:
    basename: i18n/message
    encoding: UTF-8
    cache-duration: PT1H
  security:
    user:
      name: user
      password: 1234
      roles: USER
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:spring_securityMODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
      driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schema_new.sql
      data-locations: classpath:sql/data_new.sql
      encoding: utf-8

  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 60

logging:
  level:
    org.hibernate.SQL: DEBUG