-- DROP TABLE IF EXISTS authorities CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;
--
-- CREATE TABLE users(
--     username VARCHAR(50) NOT NULL,
--     password VARCHAR(100) NOT NULL,
--     enabled BOOLEAN NOT NULL DEFAULT false,
--     primary key (username)
-- );
--
-- CREATE TABLE authorities (
--     username VARCHAR(50) NOT NULL,
--     authority VARCHAR(50) NOT NULL,
--     PRIMARY KEY (username)
-- );